#!/usr/bin/env ruby
require 'optparse'

def parse_command_line
  # parse the command line args into a hash of options
  script_name = File.basename($0)
  options = {}
      
  ARGV.options do |o|
    o.banner = "Usage: #{script_name} [options]"
    o.define_head "Clear error emails from sendgrid." 
           
    options[:run_type] = :all
        
    # TODO: add a -i for info on which workers are running  
    o.on("-e", "--env RAILS_ENV", String, "Rails environment") {|v| options[:env] = v }
    o.on_tail("-h", "--help", "Show this help message.") { puts o; exit }
    o.parse!
  end
  
  return options  
end

def main
  # process command line args
  options = parse_command_line
  
  # load the rails environment
  env = options[:env]
  ENV['RAILS_ENV'] = env if env
    
  require File.dirname(__FILE__) + '/../config/environment'

  # TODO: Use username and password
  # TODO: Use start date and end date

  require 'sendgrid'
  cie = Sendgrid::ClearInvalidEmails.new
  cie.clear_emails
end

if $0 == __FILE__
  main
end