#!/usr/bin/env ruby
require 'optparse'
require 'yaml'
require 'erb'

def parse_command_line
  # parse the command line args into a hash of options
  script_name = File.basename($0)
  options = {}
      
  ARGV.options do |o|
    o.banner = "Usage: #{script_name} [options]"
    o.define_head "Script to re-update departments." 
           
    options[:run_type] = :all
        
    # TODO: add a -i for info on which workers are running  
    o.on("-e", "--env RAILS_ENV", String, "Rails environment") {|v| options[:env] = v }
    o.on_tail("-h", "--help", "Show this help message.") { puts o; exit }
    o.parse!
  end
  
  return options  
end

def main
  # process command line args
  options = parse_command_line
  
  # load the rails environment
  env = options[:env]
  ENV['RAILS_ENV'] = env if env
    
  require File.dirname(__FILE__) + '/../../config/environment'
  
  require 'product_generator'
  pg = AlertGenerator::ProductGenerator.new

  changes = 0

  Product.find(:all, :conditions => 'department_id IS NULL').each do |p|
    f = p.feed_category
    d = pg.get_department(p.product_name, f.feed_category, f.feed_subcategory, f.feed_product_group)
    unless d.nil?
      p.department = d
      p.save!
      changes += 1
    end
  end
  
  puts "Total changes: #{changes}"
                                
end

if $0 == __FILE__
  main
end
